name: builds
on: [push]
jobs:
  reobfJar:
    runs-on: Felix
    steps:
      - uses: actions/checkout@v2
      - run: git submodule update --init --recursive
      - run: ./gradlew clean
      - run: ./gradlew build
      - run: ./gradlew publish
      - run: mkdir jars
      - run: mv BiggerReactors/build/libs/biggerreactors-* jars/
      - run: mv Phosphophyllite/build/libs/phosphophyllite-* jars/
      - uses: actions/upload-artifact@v2
        with:
          name: jars
          path: jars/*