name: builds
on: [push]
jobs:
  reobfJar:
    runs-on: Felix
    steps:
      - uses: actions/checkout@v2
      - run: ./gradlew clean
      - run: ./gradlew build
      - run: ./gradlew reobfJar
      - run: mkdir reobfJars
      - run: mv BiggerReactors/build/reobfJar/output.jar reobfJars/biggerreactors-${GITHUB_SHA::8}-reobfJar.jar
      - run: mv Phosphophyllite/build/reobfJar/output.jar reobfJars/phosphophyllite-${GITHUB_SHA::8}-reobfJar.jar
      - uses: actions/upload-artifact@v2
        with:
          name: reobfJar
          path: reobfJars/*