name: wiki
on:
  push:
    paths: 
      - "BiggerReactors/src/main/resources/data/biggerreactors/**"
jobs:
  data_to_csv:
    name: Export data to CSV
    runs-on: Felix
    steps:
      - uses: actions/checkout@v2
      - run: git submodule update --init --recursive
      - run: ./gradlew generateCoilCsv generateModeratorCsv
      - uses: actions/upload-artifact@v2
        with:
          name: CSV
          path: BiggerReactors/build/data/*.csv
  data_to_wikimedia:
    name: Export data to Wikimedia table format
    runs-on: Felix
    steps:
      - uses: actions/checkout@v2
      - run: git submodule update --init --recursive
      - run: ./gradlew generateModeratorWikimedia generateCoilWikimedia
      - uses: actions/upload-artifact@v2
        with:
          name: WikiMedia
          path: BiggerReactors/build/data/*.txt
